plugins {
    id 'java'
}

group = 'ru.aurora'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = 'paper'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'luckperms'
        url = 'https://repo.luckperms.net/'
    }
    maven {
        name = 'placeholderapi'
        url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'
    compileOnly 'me.clip:placeholderapi:2.11.6'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

tasks.jar {
    archiveBaseName = 'AuroraChat'
}

build {
    dependsOn tasks.jar
}
